#!/usr/bin/python3
import sys
sys.argv
num_list = []
found = 0
if len(sys.argv) != 2:
    sys.exit("Script with Error")
file = open(sys.argv[1])
for row in file:
    found = 0
    # print(row[:-1])
    num_list = int(row[:-1])
    for i in range(2, 8):
        if (num_list % i == 0):
            num_1 = int(num_list / i)
            found = 1
            print("{:d}={:d}*{:d}".format(num_list, num_1, i))
            break;
    if (found == 0):
        print("{:d}={:d}*{:d}".format(num_list, num_1, 1))
file.close()
