#!/usr/bin/python3
import sys
import math

num = []
num_1 = 0
top = 0
found = 0

if len(sys.argv) != 2:
    sys.exit("Script with Error")
file = open(sys.argv[1])

for row in file:
    found = 0
    # print(row[:-1])
    num = int(row[:-1])
    if num >= 4:
        top = int((num) / 2)
    else:
        top = num
    for i in range(2, top):
        if (num % i == 0):
            num_1 = int(num / i)
            found = 1
            if num_1 * i == num:
              print("{:d}={:.0f}*{:d}".format(num, num_1, i))
              break;
    if (found == 0):
        print("{:d}={:}*{:d}".format(num, num, 1))
file.close()
