#!/usr/bin/python3
import sys

def factorize(num):
    factors = []
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            factors.append((i, num // i))
            return factors

def main(filename):
    with open(sys.argv[1], 'r') as file:
        for line in file:
            num = int(line)
            factorizations = factorize(num)
            for factorization in factorizations:
                p, q = factorization
                print(f"{num}={p}*{q}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python factors.py <file>")
        sys.exit(1)
    filename = sys.argv[1]
    main(filename)

